export enum OrchestrationEvents {
  $$INIT = '$$INIT',
  DEFINE_CUSTOM_ELEMENTS = 'DEFINE_CUSTOM_ELEMENTS',
  ORCHESTRATE = 'ORCHESTRATE',
  ORCHESTRATION_ERROR = 'ORCHESTRATION_ERROR',
  PROCESS_ORCHESTRATION_QUEUE = 'PROCESS_ORCHESTRATION_QUEUE',
  REROUTE_URL_ONLY = 'REROUTE_URL_ONLY',
  SET_ORCHESTRATOR_LISTENING = 'SET_ORCHESTRATOR_LISTENING',
}
