export enum OrchestrationEvents {
  $$INIT = '$$INIT',
  CALL_HOOKS = 'CALL_HOOKS',
  CALL_HOOKS_ERROR = 'CALL_HOOKS_ERROR',
  CALL_HOOKS_RESOLVED = 'CALL_HOOKS_RESOLVED',
  DEFINE_CUSTOM_ELEMENTS = 'DEFINE_CUSTOM_ELEMENTS',
  PROCESS_ORCHESTRATION_QUEUE = 'PROCESS_ORCHESTRATION_QUEUE',
  RENDER = 'RENDER',
  REROUTE_URL_ONLY = 'REROUTE_URL_ONLY',
  SET_ORCHESTRATOR_LISTENING = 'SET_ORCHESTRATOR_LISTENING',
  START = 'START',
  STOP = 'STOP',
}
