export enum OrchestrationEvents {
  CALL_HOOKS = 'CALL_HOOKS',
  CALL_HOOKS_ERROR = 'CALL_HOOKS_ERROR',
  CALL_HOOKS_SUCCESS = 'CALL_HOOKS_SUCCESS',
  PROCESS_ORCHESTRATION_QUEUE = 'PROCESS_ORCHESTRATION_QUEUE',
  REROUTE_URL_ONLY = 'REROUTE_URL_ONLY',
  SET_ORCHESTRATOR_LISTENING = 'SET_ORCHESTRATOR_LISTENING',
  START = 'START',
  STOP = 'STOP',
}
