export enum Statuses {
  REGISTERED = 'REGISTERED',
  LOADED = 'LOADED',
  LOAD_ERROR = 'LOAD_ERROR',
  BOOTSTRAPPED = 'BOOTSTRAPPED',
  BOOTSTRAP_ERROR = 'BOOTSTRAP_ERROR',
  MOUNTED = 'MOUNTED',
  MOUNT_ERROR = 'MOUNT_ERROR',
  RUNNING = 'RUNNING',
  STOPPED = 'STOPPED',
  UNMOUNTED = 'UNMOUNTED',
  UNMOUNT_ERROR = 'UNMOUNT_ERROR',
  SKIPPED = 'SKIPPED',
}
