version: '3'

services:
  auth:
    build:
      context: ./services/auth
      args:
        NODE_ENV: 'production'
    container_name: mfe-service-auth
    command: npm start
    tty: true
    ports:
      - 3002:3002
      - 35729:35729
    volumes:
      - $PWD/view/node_modules:/home/view/node_modules
      - $PWD/view:/home/view

  data:
    build:
      context: ./services/data
      args:
        NODE_ENV: 'production'
    container_name: mfe-service-data
    command: npm start
    restart: always
    tty: true
    ports:
      - 3004:3004

  i18n:
    build:
      context: ./services/i18n
      args:
        NODE_ENV: 'production'
    container_name: mfe-service-i18n
    command: npm start
    tty: true
    ports:
      - 3005:3005

  app:
    build:
      context: ./app
      args:
        NODE_ENV: 'production'
    container_name: mfe-app
    command: npm start
    tty: true
    ports:
      - 3000:3000
