export enum RegistrationEvents {
  ADD_SERVICE = 'ADD_SERVICE',
  REGISTER = 'REGISTER',
  REGISTRATION_ERROR = 'REGISTRATION_ERROR',
  REGISTRATION_SUCCESS = 'REGISTRATION_SUCCESS',
  REMOVE_SERVICE = 'REMOVE_SERVICE',
  SET_REGISTRY_LISTENING = 'SET_REGISTRY_LISTENING',
}
