export enum ServiceOrchestrationEvents {
  CHANGE_STATUS = 'CHANGE_STATUS',
  FETCH_MANIFEST = 'FETCH_MANIFEST',
  FETCH_MANIFEST_ERROR = 'FETCH_MANIFEST_ERROR',
  FETCH_MANIFEST_SUCCESS = 'FETCH_MANIFEST_SUCCESS',
  IMPORT = 'IMPORT',
  IMPORT_ERROR = 'IMPORT_ERROR',
  IMPORT_SUCCESS = 'IMPORT_SUCCESS',
  SET_SERVICE_LISTENING = 'SET_SERVICE_LISTENING',
}
