export enum ServiceStatuses {
  REGISTERED = 'REGISTERED',
  LOADED = 'LOADED',
  LOAD_ERROR = 'LOAD_ERROR',
  BOOTSTRAPPED = 'BOOTSTRAPPED',
  BOOTSTRAP_ERROR = 'BOOTSTRAP_ERROR',
  MOUNTED = 'MOUNTED',
  MOUNT_ERROR = 'MOUNT_ERROR',
  UNMOUNTED = 'UNMOUNTED',
  UNMOUNT_ERROR = 'UNMOUNT_ERROR',
  UNLOADED = 'UNLOADED',
  UNLOAD_ERROR = 'UNLOAD_ERROR',
  SKIPPED = 'SKIPPED',
}
